### ISSUE TITLE
Issues Running via Link

### ISSUE THREAD

**Issue by eswaranand1997** [oculus-samples/Unity-Discover#11]
Had previously opened: https://github.com/oculus-samples/Unity-Discover/issues/7

Reporting back with requested details. Tested again on v60. Here's the results

testing on Quest Pro over Link and Quest 2. 
Link App version: Oculus App Version 60.0.0.162.352 (60.0.0.162.352)
Headset Version: 60.0.0.193.366.548441753

When building to both devices to run natively, application works fine. When hosting a room, the device shows the current scene setup and asks for confirmation about the scene setup. 

When running on PCVR Link in Unity Editor, this request does not pop up. After both users load in, they are not colocated.

Other scene api samples dont seem to work as well. The SceneManager and BouncingBall samples from the [StarterSamples ](https://github.com/oculus-samples/Unity-StarterSamples) package also do not work properly over link. Scenemanager shows no volumes on Link while running natively, shows anchors and bounding boxes over the defined scene objects.

Here's the device logs from the QPro while running Discover in Editor. 
[odh_logs_2023-12-29 23.52.07.199.txt](https://github.com/oculus-samples/Unity-Discover/files/13796559/odh_logs_2023-12-29.23.52.07.199.txt)

Some relevant warnings from editor 
<img width="991" alt="image" src="https://github.com/oculus-samples/Unity-Discover/assets/78716202/b5119c86-4e9f-4c24-b7ca-6ac28289be91">

<img width="993" alt="image" src="https://github.com/oculus-samples/Unity-Discover/assets/78716202/20ebe8ec-d1d5-4be0-a5bf-efc52048ce31">

**Comment by tdmowrer** [comment]
Hi @eswaranand1997 and apologies for the extreme delay in response here. Taking another look at this, I was going to ask for the Editor logs instead of device logs (which generally are more relevant to Link-related failures like this). I can see more of the problem in your second screenshot -- creating the "space user" failed, which subsequently caused `xrShareSpacesFB` to fail.

If you are still seeing this issue, it might help if you could provide the Editor logs as it might explain why that call is failing.

**Comment by jasonmeisel** [comment]
If you are still running into this problem with the latest version of Link, please re-open the issue.
