### ISSUE TITLE
Transmitting and Inverting Player/Object Transforms in Co-Located Space

### ISSUE THREAD

**Issue by kingdomax** [oculus-samples/Unity-Discover#14]
Greetings here,

I am currently prototyping a multi-user co-located application. My objective is to achieve functionality similar to this project, but with a focus on utilizing Unity's Netcode and com.unity.xr.meta-openxr. (note: I acknowledge that shared spatial anchor is not yet supported by the packages I'm using.)

In my research, specifically through the Unity-Discover documentation https://developer.oculus.com/documentation/unity/unity-learn-mixed-reality-through-discover/, I encountered a section discussing the necessity of transmitting the relative transforms of each player's camera rig and objects to a spatial anchor across the network. This approach requires inverting the transform on the receiving end to ensure objects appear in a shared space for all users.

However, I am having difficulty locating the specific component or script that facilitates this mechanism. The closest thing I could find is `AllignmentAnchorManager.AlignmentCoroutine()`, which seems to align the player's position with a spatial anchor when entering a networked scene, but does not cover the entirety of the functionality I need.

Could anyone provide guidance or pinpoint the parts that I should examine to implement this feature? Any assistance in understanding how to correctly transmit and invert transforms for a shared spatial experience would be greatly appreciated.

Thank you for your time, and hope you have a pleasant day 😄

**Comment by AlexThiv** [comment]
Hi @kingdomax,

I'll try to summarize that section of the documentation, hopefully it will help you in your case. The host places a shared anchor in the world and then reorient themselves to that anchor (moving that anchor essentially to be the origin. The alignment code as you mention is found in the [AlignementCoroutine](https://github.com/oculus-samples/Unity-Discover/blob/main/Packages/com.meta.xr.sdk.colocation/Anchors/AlignmentAnchorManager.cs#L72-L77), particularly the InverseTransformPoint function. When another user joins they get the same shared anchor (in discover context), that shared anchor is placed and oriented at the same physical place in the room. That client can then run the same logic to align themselves to that anchor. At that point the relative position of all spawned objects will be in the same physical position.

Now in your case, openxr doesn't yet support shared anchors, so that part gets a bit tricky. What you could do is find a specific feature in the physical room, like the corner of a table and have the user place an object there, make sure to know what is the orientation of the object, ideally aligned as close as possible with the edges of the table (adding a spatial anchor will ensure it stays in sync with the physical world). Next you align the host to that placed object. Then you do the same with the client joining. If they placed the anchor object in the same position and orientation, they should have a pretty close alignment to each other.

There is also a deep dive into how the Colocation works in this documentation https://developer.oculus.com/documentation/unity/unity-shared-spatial-anchors-walkthrough/

We also have this project [Unity-LocalMultiplayerMR](https://github.com/oculus-samples/Unity-LocalMultiplayerMR) that has an example using NGO, it's using the latest version of the colocation package (still with shared spatial anchor though).

I hope this helps you, let me know if we can clarify anything further.

**Comment by kingdomax** [comment]
That documentation led me to believe there was an additional step involving the manual transmission of relative transforms.

@AlexThiv If I understand correctly, each user only needs to align with the spatial anchor **once** upon entering the scene. After this initial setup, all objects positions will be sync automatically adjusted across the networked scene, eliminating the need for further alignment or the manual transmission of any special relative transforms through the network (i.e., the usual object transforms will still be sent via the network solution).

Thank you very much for clarifying this point so promptly :+1:

**Comment by AlexThiv** [comment]
Yes the objects still need to sync there position over the network when they are spawned or moved, but there positions will be relative to that anchor which would be at the same physical location for all users.
