### ISSUE TITLE
Integrating Colocation Package

### ISSUE THREAD

**Issue by kingdomax** [oculus-samples/Unity-Discover#16]
Hello,

I decided to switch to use Meta SDK and I'm currently exploring the integration of the colocation package into my prototype, based on the suggestion [here](https://github.com/oculus-samples/Unity-Discover/issues/14#issuecomment-1931220382).

1) I'm not sure whether to use colocation package directly from this repository or opt for the [Unity-LocalMultiplayerMR version](https://github.com/oculus-samples/Unity-LocalMultiplayerMR/tree/main/colocation-package). The documentation on [developer.oculus.com](https://developer.oculus.com/documentation/unity/unity-shared-spatial-anchor) seems to be based on the package from this project, yet I've observed that newer projects like Unity-CrypticCabinet are utilizing Unity-LocalMultiplayerMR's version. Additionally, I've noticed the absence of `AlignmentAnchorManager` in the Unity-LocalMultiplayerMR package, and differences in method signatures for `INetworkData` and `INetworkMessenger`. For context, NGO is the network solution I'm using.

2) I'm also curious about the feasibility of testing two app runtimes with different setups: one running the app in Unity playmode via Quest Link and another in Unity playmode via XR Simulator which using the exact [SceneRecorder data](https://developer.oculus.com/documentation/unity/xrsim-scene-recorder/) from the headset in the first setup. Will shared spatial anchor work in this interoperability manner?

3) Next setup, if running one app session in Unity's play mode through Quest Link, and another session directly on a device as a standalone APK build. Can shared spatial anchor service operate successfully in this setup?

4) Regarding testing shared spatial anchor on Quest device, after building the APK, assuming the project is correctly set up on the Oculus developer dashboard (https://developer.oculus.com/), do I need to upload build file to a channel on developer hub and then download it onto the device from app store? Or can I simply sideload the APK file onto the device?

5) I've noticed a discrepancy between the anchor UUIDs in `XR Simulator's app_anchors.json`, `XR Simulator's local_sharing_server.exe`, compared to what I'm debugging from the code using `OVRSpatialAnchor.Uuid`. The first three sections of the ID seem to be scrambled. For example, an UUID identified by OVRSpatialAnchor.Uuid as `c695fda5-7d0c-436e-8e26-f3efa5600884` appears as `a5fd95c6-0c7d-6e43-8e26-f3efa5600884` in app_anchors.json and local_sharing_server.exe. Why are these values not matching?

**Comment by kingdomax** [comment]
6. Actually, I encountered issues while integrating [colocation package version 1.0.0](https://github.com/oculus-samples/Unity-LocalMultiplayerMR/tree/main/colocation-package) and testing my project in Unity play mode using the XR Simulator (duplicating 2 app sessions with ParallelSync). It appears the shared spatial anchor service doesn't function as expected. The behavior of the mock server, `local_sharing_server.exe`, varies with each version of the XR Simulator used. I'm trying to pinpoint the problem; is it related to my code implementation, the colocation package, or XR Simulator itself? I also ran tests with [Unity-Discover](https://github.com/oculus-samples/Unity-Discover), [Unity-LocalMultiplayerMR](https://github.com/oculus-samples/Unity-LocalMultiplayerMR), and [Unity-CrypticCabinet](https://github.com/oculus-samples/Unity-CrypticCabinet), using the simulator versions included with those projects. Below are screenshots illustrating the inconsistent behavior observed with the mock server:

**My project, XR Simulator version 62, Colocation package version 1.0.0**
_(Zero anchor sharing and sharing target user is consistently assigned to value 184467...0843)_
![myproject-v62](https://github.com/oculus-samples/Unity-Discover/assets/6430428/37737580-fcc9-4495-8b7e-36f7add704fc)

**My project, XR Simulator version 57, Colocation package version 1.0.0**
_(Correct anchor sharing but sharing target user is still assigned to value 184467...0843)_
![myproject-v57](https://github.com/oculus-samples/Unity-Discover/assets/6430428/e192300d-387a-4524-b13d-d99754c7b0cd)

**Unity-CrypticCabinet,, XR Simulator version 60, Colocation package version 1.0.0**
_(Sharing target user is always a 0 value.)_
![crypticcabinet-v60](https://github.com/oculus-samples/Unity-Discover/assets/6430428/347ffb52-b0db-4177-a10a-315785768f43)

**Unity-LocalMultiplayerMR NGO sample,, XR Simulator version 59, Colocation package version 1.0.0**
_(This even worse there are errors in Unity console and mock server show misbehavior which same userid query the anchor twice.)_
![ngosample-v59](https://github.com/oculus-samples/Unity-Discover/assets/6430428/c20ceb65-18c1-49d2-8f17-a867c1d9c016)
![ngosample-error](https://github.com/oculus-samples/Unity-Discover/assets/6430428/68e1a939-ca8c-48f0-82a1-029094de910b)

**Unity-Discover, XR Simulator version 57, Colocation package version 0.1.0-preview**
_(The only combination that seems to work as expected.)_
![discover-v57](https://github.com/oculus-samples/Unity-Discover/assets/6430428/89ee5aec-a70e-47da-8f19-84aa1663060c)

Thank you very much for any advice or recommendations. I realize this is quite a wall of text, but I hope it will be useful to others encountering similar issues in the future.

**Comment by kingdomax** [comment]
Responding to my own issue here, hoping this information will be helpful to anyone who finds themselves in a similar situation.

1) I recommend using the colocation package from the [Unity-LocalMultiplayerMR repository](https://github.com/oculus-samples/Unity-LocalMultiplayerMR/tree/main/colocation-package). This is the latest version `(version 1.0)`, which is an improvement over what's available in the Unity-Discover repository. The updated version simplifies the integration process by reducing boilerplate code. However, it's important to note that this package performs [alignment operations every frame](https://github.com/oculus-samples/Unity-LocalMultiplayerMR/blob/main/colocation-package/Runtime/AlignCameraToAnchor.cs#L17), which could lead to frame drops and unusual physics behaviors. Careful management of this aspect is crucial.

2) If you're running your app through the XR Simulator, spatial anchor requests (such as saving or querying anchors from a cloud location) will be directed to a local mock server `(i.e., local_sharing_server.exe)`. In contrast, when running your app via Quest Link or as a standalone APK, these requests will go to the Meta cloud as expected. So, no, this scenario setup won't work.

3) Running one app session in Unity play mode through Quest Link and another directly on a device as a standalone APK build works flawlessly for shared spatial anchor services.

4) Even after building your APK, you must upload it to the Oculus developer dashboard to obtain entitlement. Without this step, the feature will not function properly.

5) Regarding the anchor UUID discrepancies, I haven't been able to investigate this further. Despite slight numerical differences, it appears that the anchors are still recognized as the same.

**Comment by AlexThiv** [comment]
Hi @kingdomax,

1. We are working on integrating the Colocation package you mention, the one in this project is an earlier version of it. We also have a temporary fix for every frame alignment in [Cryptic Cabinet](https://github.com/oculus-samples/Unity-CrypticCabinet/blob/main/Assets/CrypticCabinet/Scripts/Colocation/ColocationDriverNetObj.cs#L154-L161)
2. It is something we have talked about with the XR Simulator team, thanks for raising it.
3. Glad to hear, this is the expected behaviour.
4. Correct you need to send only an initial apk to anyt channel of your project for the features to work and get entitlement. After that you can push the apk directly to your device
5. I'll bring this up with the XR Simulator team and get back to you on this.

Thanks for raising these questions.

**Comment by benbatya-fb** [comment]
Hi @kingdomax , thank you for your questions:

about #2: XrSim currently has a different internal representation of shared anchors from mobile/links representation. Hence, the need for local sharing server. That might change in the future, but that's the current situation. 

About #5, unfortunately, the unity integration uses Guid to contain XrUuid types and its toString() follows Guid rules instead of treating them as uint8_t[16] . Hence, the scramble.  It should not affect the comprison of anchor ids . Unreal doesn't have the problem. If it's an issue for testing, then reverse the little endian interpretation of the ID, and it will match. 

Thanks!

**Comment by AlexThiv** [comment]
@kingdomax 

re 2) Re reading your question here. Shared spatial anchors will not be able to localize in different rooms and in the context of discover it would make the joining client as a remote player. So to answer your question, yes you can run them in parallel, but it wouldn't get the shared anchor due to different storage, but it wouldn't matter as the expected result would be for the players to detect that they are in different rooms.

**Comment by AlexThiv** [comment]
We updated the project with latest release colocation package as well as added information on updating an apk before using certain features like shared spatial anchors.
