### ISSUE TITLE
Real-time shadows missing

### ISSUE THREAD

**Issue by carloposo** [oculus-samples/Unity-Discover#32]
Hello,
I am not able to cast any real-time shadows. Is this normal or am I missing something?
My objects' have all the Cast Shadow option enabled. I am using the Meta/Depth/URP/Occlusion Lit shader.

Thanks!

**Comment by carloposo** [comment]
I just managed to get this by tweaking the Quest_Pipeline Asset.

https://github.com/user-attachments/assets/bf7047b3-0354-4c84-acdd-f682afa77cb9

![Immagine 2024-09-24 184119](https://github.com/user-attachments/assets/38445491-1c02-4db7-87c6-e5ba2b81c847)

**Comment by AlexThiv** [comment]
You probably updated the main light in the Discover scene to cast shadows. Seems like you might have it set to hard instead of soft shadow. Another potential change to have better quality would be to reduce the Max Distance in the settings.
This is not a specific item to discover but rather a Unity URP question. You can find resources on URP about shadows here https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@12.0/manual/Shadows-in-URP.html

If you have other Discover specific issues you can always file additional issues.
