### ISSUE TITLE
Unity 6 compatibility

### ISSUE THREAD

**Issue by carloposo** [oculus-samples/Unity-Discover#34]
Hello!
Quick question: is Discover compatible with the latest Unity 6 release?
Carlo

**Comment by AlexThiv** [comment]
Hi @carloposo,
Yes it will work with Unity 6, but there is some steps to do due to the migration to the updated engine.
You will encounter the standard Unity engine update popups that you can just accept, including the update of material for URP.

Then you will need go and update the AndroidManifest as the activity name is different.
![image](https://github.com/user-attachments/assets/3fd6400a-c5cf-44b8-9176-053688ba0b95)

You will also need to apply the fix from the Project Setup tool
![image](https://github.com/user-attachments/assets/cf8298d3-e19a-4659-a7fa-84fa64402d21)


Then you will be able to make a build and test it on device.
