### ISSUE TITLE
Saving Prefab to immutable folder is not allowed

### ISSUE THREAD

**Issue by Steelswarm** [oculus-samples/Unity-Discover#5]
Although I keep getting this error, everything seems to be working as intended, although I've been trying to fix it to no avail.
The error pops up on:
1- "Packages/com.meta.xr.sdk.interaction/Runtime/Prefabs/Ray/ControllerRayInteractor.prefab" 
2- "Packages/com.meta.xr.sdk.interaction/Runtime/Prefabs/Ray/HandRayInteractor.prefab"
Any idea what the issue might be?

**Comment by mazvalente** [comment]
I see what's causing this. The Unity-Discover project is using the new way of releasing SDKs, the Unity Package Manager. Since those packages are immutable by default, you're getting this error when you select the prefab because it attempts to auto-wire a target for ConrollerRef._controller and HandRef._hand respectively on inspector selection which is causing it to attempt to edit an immutable folder.

I'll pass this on and see if we can get a fix for it, but it's not going to break anything in your project, and as soon as you copy the prefab into your scene hierarchy the issue should disappear.

**Comment by jasonmeisel** [comment]
This should be fixed as of f2a09ab.
